import argparse
import os
import sys

import mlflow
import tarfile
import shutil
import joblib
from pathlib import Path
sys.path.append(os.path.join(os.path.dirname(__file__), '../..'))
from src.utils.config_manager import get_mlflow_tracking_uri


def package_model(mlflow_run_id: str, output_file: str, mlflow_tracking_uri: str = None):
    print(f"Packaging model from MLflow run {mlflow_run_id}...")

    tracking_uri, uri_source = get_mlflow_tracking_uri(mlflow_tracking_uri)
    mlflow.set_tracking_uri(tracking_uri)

    print(f"MLflow Tracking: {tracking_uri}")
    print(f"(from {uri_source})")

    temp_dir = Path("temp_model")
    temp_dir.mkdir(exist_ok=True)

    try:
        model_uri = f"runs:/{mlflow_run_id}/model"
        print(f"Downloading from: {model_uri}")

        try:
            model = mlflow.sklearn.load_model(model_uri)
            print(f"Model loaded successfully: {type(model).__name__}")
        except Exception as e:
            print(f"ERROR loading model: {e}")
            print(f"Troubleshooting:")
            print(f"- Check run ID is correct: {mlflow_run_id}")
            if tracking_uri == "databricks":
                print(f"- Check Databricks credentials (DATABRICKS_HOST, DATABRICKS_TOKEN)")
            print(f"- Verify model was logged to MLflow")
            raise

        model_path = temp_dir / "model.joblib"
        joblib.dump(model, model_path)
        print(f"Model saved: {model_path}")

        # Bundle the fitted preprocessor so serving reuses the exact scaler /
        # time-normaliser from training (prevents train/serve skew).
        print(f"Downloading preprocessor from MLflow...")
        preprocessor_path = mlflow.artifacts.download_artifacts(
            run_id=mlflow_run_id, artifact_path="preprocessor/preprocessor.joblib"
        )
        shutil.copy(preprocessor_path, temp_dir / "preprocessor.joblib")
        print(f"Preprocessor bundled")

        repo_root = Path(__file__).resolve().parents[2]

        # Bundle the shared feature-engineering module — inference.py imports it so
        # the served feature set is generated by the same code used at train time.
        feature_module = repo_root / "src" / "features" / "feature_engineering.py"
        shutil.copy(feature_module, temp_dir / "feature_engineering.py")
        print(f"Feature engineering module bundled")

        inference_script = repo_root / "src" / "models" / "inference.py"
        if not inference_script.exists() or inference_script.stat().st_size == 0:
            raise FileNotFoundError(
                f"inference.py is missing or empty at {inference_script}; cannot package."
            )
        shutil.copy(inference_script, temp_dir / "inference.py")
        print(f"Inference script copied")

        # Pin serving deps to the versions the model was trained with, otherwise
        # the pickle may fail to load at serving time.
        requirements_content = (
            "scikit-learn==1.7.2\n"
            "numpy==2.2.6\n"
            "pandas==2.3.3\n"
            "joblib==1.5.3\n"
        )
        with open(temp_dir / "requirements.txt", 'w') as f:
            f.write(requirements_content)
        print(f"Requirements.txt created")

        print(f"Creating model.tar.gz...")
        with tarfile.open(output_file, "w:gz") as tar:
            for item in temp_dir.iterdir():
                tar.add(item, arcname=item.name)

        file_size_mb = os.path.getsize(output_file) / 1024 / 1024
        print(f"Model packaged successfully")
        print(f"File: {output_file}")
        print(f"Size: {file_size_mb:.2f} MB")

    finally:
        if temp_dir.exists():
            shutil.rmtree(temp_dir)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Package model for SageMaker')
    parser.add_argument('--mlflow-run-id', required=True, help='MLflow run ID')
    parser.add_argument('--output-file', required=True, help='Output tar.gz file')
    parser.add_argument('--mlflow-tracking-uri', required=False, default=None,
                        help='MLflow tracking URI (use "databricks" for Databricks)')

    args = parser.parse_args()

    package_model(args.mlflow_run_id, args.output_file, args.mlflow_tracking_uri)